#!/home/blogenv/bin/python
# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-13 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_auto_20171213_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myphoto',
            name='photo',
            field=models.ImageField(upload_to='avatar/myphoto/%Y/%m/%d/'),
        ),
    ]
