#!/home/blogenv/bin/python
# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-17 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0003_auto_20171213_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myphoto',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='点赞量'),
        ),
    ]
